footer:
  framework: Framework
  theme: Theme

copy:
  success: 可以Copy,但是不要乱用哦
  error: Copy error
  noSupport: The browser does not support

page:
  articles: Articles
  tag: Tag
  category: Category
  archives: Archives

card_post_count: comments

sticky: Sticky
no_title: No title

post:
  created: Created
  updated: Updated
  wordcount: Word count
  min2read: Reading time
  min2read_unit: min
  page_pv: Post View
  comments: Comments
  copyright:
    author: Author
    link: Link
    copyright_notice: Copyright Notice
    copyright_content: '著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。'
  recommend: Related Articles
  edit: Edited on

search:
  title: Search
  load_data: Loading the Database
  algolia_search:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}."
    hits_stats: '${hits} results found in ${time} ms'

  local_search:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

pagination:
  prev: Previous Post
  next: Next Post

comment: Comment

aside:
  articles: Articles
  tags: Tags
  categories: Categories
  card_announcement: 关于我
  card_categories: Categories
  card_tags: Tags
  card_archives: Archives
  card_recent_post: Recent Post
  card_webinfo:
    headline: Info
    article_name: Article
    runtime:
      name: Run time
      unit: days
    last_push_date:
      name: Last Push
    site_wordcount: Total Count
    site_uv_name: UV
    site_pv_name: PV
  more_button: More
  card_newest_comments:
    headline: Newest Comments
    loading_text: loading...
    error: Unable to get the data, please make sure the settings are correct.
    zero: No Comment
    image: image
    link: link
    code: code
  card_toc: Catalog

date_suffix:
  just: Just
  min: minutes ago
  hour: hours ago
  day: days ago
  month: months ago

donate: Donate
share: Share

rightside:
  readmode_title: Read Mode
  translate_title: Toggle Between Traditional Chinese And Simplified Chinese
  night_mode_title: Toggle Between Light And Dark Mode
  back_to_top: Back To Top
  toc: Table Of Contents
  scroll_to_comment: Scroll To Comments
  setting: Setting
  aside: Toggle between single-column and double-column
  chat: Chat

copy_copyright:
  author: Author
  link: Link
  source: Source
  info: 著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

Snackbar:
  chs_to_cht: Traditional Chinese Activated Manually
  cht_to_chs: Simplified Chinese Activated Manually
  day_to_night: Dark Mode Activated Manually
  night_to_day: Light Mode Activated Manually

loading: Loading...

error404: Page not found
